### ISSUE TITLE
Apache 2.2 configured new page

### ISSUE THREAD

**Issue by Payne-X6** [LobbyOS/lobby#11]
Used Bash install script..
Missing Symlink in /etc/apache2/sites-enabled from /etc/apache2/sites-available/lobby.conf.
In that file using config parameter "Require all granted" that is unavailable on Apache 2.2, but available on Apache 2.4.

**Comment by subins2000** [comment]
Thanks again for reporting the bug. :smiley: 
This bug has been moved to corresponding place : https://github.com/LobbyOS/deb-installer/issues/1
