### ISSUE TITLE
Download any app

### ISSUE THREAD

**Issue by Payne-X6** [LobbyOS/lobby#12]
When downloading app get this errors (about 50times, maybe more):

``` bash
[Sun Jan 24 23:31:57 2016] [error] [client 127.0.0.1] PHP Warning:  Missing argument 5 for {closure}() in /var/www/Lobby/admin/download.php on line 62, referer: http://lobby.os/admin/install-app.php?id=millionaire&csrf_token= xxxxxxxxxxx
```

It's error.log message....

I did covered token (don't know if it could be security problem, my web development skills = 0)... But I'm curious about this "OS"...

**Comment by subins2000** [comment]
Thank you very much for reporting the error. :smile: 
This bug applies to systems that has newer versions of cURL : http://stackoverflow.com/a/26622217/1372424

I fixed it by this commit : https://github.com/LobbyOS/lobby/commit/55a642c8558ec990d937f5d09b5ab67fcb32bc14#diff-40c4f59dce3e25e5bfda94a0690dfa5d

**Comment by subins2000** [comment]
To make it work, you have to reinstall Lobby : https://lobby.subinsb.com/download
