### ISSUE TITLE
iEdit when file created

### ISSUE THREAD

**Issue by Payne-X6** [LobbyOS/lobby#13]
When I created file, I get some error.

``` bash
Fatal error: Cannot access self:: when no class...
I did solve it by changing line 131 in file includes/src/Darabase.php..
\- array_walk_recursive($return, function(&$c){ $c = self::filt($c); });
\+ array_walk_recursive($return, function(&$c){ $c = DB::filt($c); });
```

I didn't study that code so I don't know why but it works... Again, Apache 2.2..

**Comment by Payne-X6** [comment]
It's becouse of lambdas... I see now that you have in requirements PHP 5.3... I should update apache... sorry...

**Comment by subins2000** [comment]
Even though it worked for you, I have change the code : https://github.com/LobbyOS/lobby/commit/69e9383d5603cdd9229987ade902321fc3674970#diff-7f83c195dd4faf1e34cab6fb4b3d1def

**Comment by suriyaa** [comment]
@subins2000: :+1:
