### ISSUE TITLE
Creating LobbyOS apps

### ISSUE THREAD

**Issue by suriyaa** [LobbyOS/lobby#14]
Hi there, :smile:

I'm one of the main official developer for the LobbyOS system.

I want to ask @subins2000 if there are any tutorials for newcomers, like creating apps for LobbyOS.

**Comment by subins2000** [comment]
The developer docs has it : https://lobby.subinsb.com/docs/dev

But it's more like components and not exactly a tutorial. I'll be making one and posting it on http://subinsb.com

**Comment by suriyaa** [comment]
:+1:
