### ISSUE TITLE
Enable / Disable functions

### ISSUE THREAD

**Issue by suriyaa** [LobbyOS/lobby#17]
@subins2000

---

Make sure that users can enable and disable functions!

For example activating SQL database and disabling cURL.

_Yours,_
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:

**Comment by subins2000** [comment]
I'm currently adding SQLite DB support to Lobby. So users can choose MySQL or SQLite.

Also, checks with server can be disabled by adding `
'server_check' => false
` in config.php

**Comment by SuriyaaKudoIsc** [comment]
:+1:

**Comment by suriyaa** [comment]
:+1:
