### ISSUE TITLE
Lobby Settings - Timezone

### ISSUE THREAD

**Issue by suriyaa** [LobbyOS/lobby#22]
@LobbyOS/maintainers 

---
- I Updated to the latest Lobby server version
- I Read the CONTRIBUTION file at https://github.com/LobbyOS/lobby/blob/master/.github/CONTRIBUTING.markdown

Browser:
- I am on (or have tested in) **_Mozilla**_ Firefox

Operating systems:
- I am on (or have tested on) **_Sulinos**_ GNU/Linux
- I am on (or have tested on) **_alOS**_
- I am on (or have tested on) **_suriyaaOS**_ GNU/UNIX
- I am on (or have tested on) **_Windows**_ 10+

---
## My Reproduction Steps

> My localhost site: http://testserver.isc/lobby/0.9.2/admin/settings.php

![fireshot screen capture 124 - change settings - lobby - testserver_isc_lobby_0_9_2_admin_settings_php](https://cloud.githubusercontent.com/assets/5073946/18033431/6b71149a-6d24-11e6-8178-e26d18c8d694.png)
## The Output I Wanted

The `Timezone` settings should be automatically set to **`System Default`** instead of _`Africa/Blantyre`_!

![fireshot screen capture 127 - change settings - lobby - testserver_isc_lobby_0_9_2_admin_settings_php](https://cloud.githubusercontent.com/assets/5073946/18033437/8ce25c88-6d24-11e6-8c75-1aed258f9f4a.png)

**Comment by subins2000** [comment]
"System default" means UTC timezone.
During installation process, Lobby determines your UTC timezone offset (UTC
- 1) and find a PHP compatible timezone with that offset.

In your case the Africa/Blantyre is the first on the list that has the
offset of Munich's. So, really Lobby is actually setting the correct
timezone even though the location is different.

**Comment by suriyaa** [comment]
Ok. :sweat_smile:
