### ISSUE TITLE
I need write access

### ISSUE THREAD

**Issue by suriyaa** [LobbyOS/lobby#3]
Hi @subins2000, :smile: 

_I don’t have write access to editing a file in this project._ :worried:

**Can you give me (admin) rights** under https://github.com/LobbyOS/lobby/settings/collaboration :question:

Thanks!

Yours,
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:

**Comment by subins2000** [comment]
I Made you the admin. Welcome to the Lobby Community. :D

**Comment by anandubajith** [comment]
:+1: 
i am thinking of making a lobby-design package , which changes the whole UI of lobby and support theming, what is your opinon?

**Comment by subins2000** [comment]
Moved to new issue : https://github.com/LobbyOS/lobby/issues/4

**Comment by suriyaa** [comment]
:+1:
