### ISSUE TITLE
PHP error - Cannot modify header information

### ISSUE THREAD

**Issue by suriyaa** [LobbyOS/lobby#6]
Hello _LobbyOS developer community_, :smile: 

I got a **PHP error while trying to install LobbyOS** on my testing website:

```
http://suriyaakudo.bplaced.net/lobby/admin/install.php
Warning: Cannot modify header information - headers already sent by (output started at /users/suriyaakudo/www/lobby/includes/src/Lobby.php:141) in /users/suriyaakudo/www/lobby/includes/src/Lobby.php on line 142
```

![screenshot 2015-09-27 09 20 55](https://cloud.githubusercontent.com/assets/5073946/10121710/acf04b0e-64f9-11e5-95ee-51e4fc9eb20c.png)

_Link: http://suriyaakudo.bplaced.net/lobby/_

What's the problem :grey_question: 

_Yours,_
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:

**Comment by subins2000** [comment]
It was a silly mistake. Remove `
echo $url;
` in \Lobby::redirect() function.

**Comment by suriyaa** [comment]
It works! :smiley: 
Thanks. :+1:
