### ISSUE TITLE
Use curl if developers or people want

### ISSUE THREAD

**Issue by suriyaa** [LobbyOS/lobby#7]
Hi again, :smile: 

_I tried to install Lobby on my testing website (link: http://suriyaakudo.bplaced.net/lobby):_

![screenshot 2015-09-28 18 15 17](https://cloud.githubusercontent.com/assets/5073946/10141709/55be4046-660e-11e5-97ef-ec8416a9a541.png)

**I realized that many developers / people are not running an own server or a paid plan server of a server hosting company.** :unamused: **Many of those server didn't have cURL :no_entry_sign: or any shell access.** :no_entry_sign: Like my webhoster "[_bplaced_](http://bplaced.net)".

> Thereby I propose that if it's possible to change the software of LobbyOS so, that users can decide whether want to use cURL or not.

_Yours,_
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:

**Comment by subins2000** [comment]
```
So, you don't have localhost to install Lobby ? Lobby is meant for localhost.
```

Anyways, your suggestion is great. WordPress use different mechanisms to do HTTP requests when cURL is not available. [http.php](https://github.com/WordPress/WordPress/blob/4d9286ad21a42fd39a520509d6c4dd3174835e39/wp-includes/class-http.php)
So, I think alternative mechanism should be implemented in Lobby and I will.

**Comment by suriyaa** [comment]
:+1:

**Comment by subins2000** [comment]
This feature was added in Lobby 0.3
Thanks for the suggestion :+1: :smile:

**Comment by suriyaa** [comment]
:+1:
