### ISSUE TITLE
Using OpenSearch

### ISSUE THREAD

**Issue by suriyaa** [LobbyOS/lobby#8]
Hi, :smile: 

why do not we use [**OpenSearch**]() :question: 

> Sample codes: http://www.opensearch.org/Specifications/OpenSearch/1.1#Examples

Yours,
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:

**Comment by subins2000** [comment]
How would OpenSearch help Lobby ? Or do you mean the Lobby Server (http://lobby.subinsb.com) ?

**Comment by suriyaa** [comment]
# OpenSearch

## Introduction

> **OpenSearch** is a collection of simple formats for the sharing of search results.

The OpenSearch description document format can be used to describe a search engine so that it can be used by search client applications.

The OpenSearch response elements can be used to extend existing syndication formats, such as RSS and Atom, with the extra metadata needed to return search results.

## For Lobby useful :question:

Yes! It can help you to publish Lobby and make it reachable for everybody.
OpenSearch shares the data to search engines like Google, Yahoo! or Bing.

**Comment by suriyaa** [comment]
OpenSearch.xml was removed in https://github.com/LobbyOS/lobby/commit/956b3370d659b366873fa200731ebbf0ed940d9a commit by subins2000.
