### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by suriyaa** [LobbyOS/lobby#9]
@subins2000 @anandubajith:

Hi guys, :smile: 

I've been thinking that _we can code_ **_better**_ with [**Travis CI**](https://travis-ci.org/). :+1: 
# What's Travis CI?

**Travis CI** lets _your team_ **test and deploy** **_with confidence**_. Trusted _by 250,000 users_, _on over 300,000 open source projects_, Travis CI _is the leading hosted continuous integration system_.
# Functions
- Supporting over 20 different languages, including Ruby, Mac/iOS, and Docker.
- Travis CI is built for everyone and because it is open source, adding support for your favorite language is easy!
- Free for open source, and with a 100 build trial for private projects, getting setup takes just 2 minutes.
- Supports your workflow!
# Helpful links for everybody!
- [Get Travis CI for GitHub](https://github.com/integrations/travis-ci) (I added a **`.travis.yml`** _file_ to this repo :sweat_smile:)
- [Travis CI for Complete Beginners](http://docs.travis-ci.com/user/for-beginners/)

**Comment by subins2000** [comment]
That's sweet. I'm working on it now

**Comment by suriyaa** [comment]
@subins2000: I added the **`.travis.yml`** file to this repo already. You should configurate it. Read the docs: https://docs.travis-ci.com/user/getting-started!
